'use strict';

const { db, uuid } = require('./index');

/**
 * Index of images a user has (generated by Wingman or sent in on WhatsApp).
 * The bytes live on disk (services/mediaStore.js); this is just the lookup.
 * Synchronous (better-sqlite3) — never await these.
 */

function create({ userId, kind, ext = 'jpg', mime = 'image/jpeg', bytes = 0, note = '' }) {
  const id = uuid();
  db.prepare(`
    INSERT INTO user_media (id, user_id, kind, ext, mime, bytes, note)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `).run(id, userId, kind, ext, mime, bytes, String(note || '').slice(0, 500));
  return get(id);
}

function get(id) {
  return db.prepare('SELECT * FROM user_media WHERE id = ?').get(id) || null;
}

function recentForUser(userId, limit = 5) {
  return db.prepare(
    'SELECT * FROM user_media WHERE user_id = ? ORDER BY created_at DESC, rowid DESC LIMIT ?',
  ).all(userId, limit);
}

/** How many images Wingman has GENERATED for this user in the last 24h. */
function generatedLastDay(userId) {
  const r = db.prepare(
    "SELECT COUNT(*) AS n FROM user_media WHERE user_id = ? AND kind = 'generated' AND created_at > datetime('now', '-1 day')",
  ).get(userId);
  return (r && r.n) || 0;
}

/** Rows older than N days (for cleanup). */
function olderThan(days) {
  return db.prepare(
    'SELECT id, ext FROM user_media WHERE created_at < datetime(\'now\', ?)',
  ).all(`-${Math.max(1, days | 0)} days`);
}

function remove(id) {
  db.prepare('DELETE FROM user_media WHERE id = ?').run(id);
}

module.exports = { create, get, recentForUser, generatedLastDay, olderThan, remove };
