import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = join(HERE, '..', 'src', 'vendor', 'hugeicons')

const VERSION = '4.2.2'

const VARIANTS = {
  stroke: '@hugeicons-pro/core-stroke-rounded',
  solid: '@hugeicons-pro/core-solid-rounded',
  duotone: '@hugeicons-pro/core-duotone-rounded',
}

const GLYPHS = [
  'BubbleChatIcon',
  'Mail01Icon',
  'Calendar01Icon',
  'Tick02Icon',
  'CheckmarkCircle02Icon',
  'Task01Icon',
  'Notification02Icon',
  'Clock01Icon',
  'Globe02Icon',
  'User03Icon',
  'UserGroup02Icon',
  'Airplane01Icon',
  'DeliveryBox01Icon',
  'Invoice01Icon',
  'FavouriteIcon',
  'Moon02Icon',
  'Sun03Icon',
  'Home01Icon',
  'DashboardSquare01Icon',
  'Briefcase02Icon',
  'ChevronLeftIcon',
  'ChevronRightIcon',
  'PlusSignIcon',
  'Shield01Icon',
  'SparklesIcon',
  'SmartPhone01Icon',
  'Delete02Icon',
  'Alert02Icon',
  'Download04Icon',
  'TruckDeliveryIcon',
  'CreditCardIcon',
  'Location01Icon',
  'PassportIcon',
  'Hotel01Icon',
  'WorkoutRunIcon',
  'Logout03Icon',
  'Cancel01Icon',
  'PaintBoardIcon',
  'VolumeHighIcon',
  'Motion01Icon',
  'TranslateIcon',
  'Car03Icon',
  'WalkingIcon',
  'Train01Icon',
  'Scooter01Icon',
  'Search01Icon',
  'News01Icon',
  'Building06Icon',
  'PencilEdit01Icon',
  'AddCircleIcon',
  'EquipmentGym03Icon',
]

async function build() {
  await mkdir(OUT_DIR, { recursive: true })

  for (const [variant, pkg] of Object.entries(VARIANTS)) {
    let mod
    try {
      mod = await import(pkg)
    } catch (err) {
      console.error(
        `\nCannot import ${pkg}. Install the pro packages first (they need the\n` +
          `Hugeicons token). See the header of scripts/vendor-icons.mjs.\n`,
      )
      throw err
    }

    const missing = GLYPHS.filter((name) => mod[name] === undefined)
    if (missing.length) {
      throw new Error(`${pkg} is missing these glyphs: ${missing.join(', ')}`)
    }

    const body = GLYPHS.map(
      (name) => `export const ${name} = ${JSON.stringify(mod[name])} as const satisfies IconSvgElement`,
    ).join('\n')

    const file =
      `// AUTO-GENERATED by scripts/vendor-icons.mjs. Do not edit by hand.\n` +
      `// Hugeicons Pro ${VERSION}, ${variant} (rounded). Regenerate: npm run vendor:icons\n` +
      `import type { IconSvgElement } from '@hugeicons/react'\n\n` +
      `${body}\n`

    const path = join(OUT_DIR, `${variant}.ts`)
    await writeFile(path, file, 'utf8')
    console.log(`wrote ${path} (${GLYPHS.length} glyphs)`)
  }
}

build().catch((err) => {
  console.error(err)
  process.exit(1)
})
